version: "3.3"
services:
  ydb:
    image: ydbplatform/local-ydb:latest
    restart: always
    ports:
      - "2135:2135"
      - "8765:8765"
      - "9092:9092"
      - "2136:2136"
    hostname: localhost
    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true
      - YDB_ENABLE_COLUMN_TABLES=true
