services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports: ["5432:5432"]
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]

  nginx:
    image: nginx:latest
    ports: ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cors.conf:/etc/nginx/cors.conf
    restart: always
    depends_on:
      - api


  api:
    build: 
      context: services/api
      dockerfile: Dockerfile

    depends_on:
      db:
        condition: service_healthy

    
    env_file:
      - .env
    restart: always
    environment:
      - PORT=80
      - POSTGRES_HOST=db


volumes:
  pgdata: