name: Deploy

on: [push, workflow_dispatch]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    STUFF_BUCKET: auth-sevice-internal-use-bucket
    FOLDER_ID: b1g4o9t4vgcbnkpunqeu
    SERVICE_ACCOUNT_ID: ajetqfs3ng6e1gjv7mdr
    SECRET_VERSION_ID: e6qe0ts1dc9g0h1h4kob
    SECRET_ID: e6q78o6erk6o9suemkh4

jobs:
  # JOB to build and test authentication code
  authentication:
    needs: changes
    if: ${{ needs.changes.outputs.authentication == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
            python-version: "3.12"

      - uses: yezz123/setup-uv@v4

      - name: Create Zip Archieve
        working-directory: services/authentication/authentication
        run: |
            uv sync
            uv pip freeze > requirements.txt

      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v2.12.0
        with:
            yc-sa-json-credentials: ${{secrets.YC_SA_JSON_CREDENTIALS}}
            folder-id: ${{env.FOLDER_ID}}
            service-account: ${{env.SERVICE_ACCOUNT_ID}}
            source-root: services/authentication/authentication
            function-name: 'authentication'
            runtime: 'python312'
            memory: '256Mb'
            entrypoint: 'main.handler'
            bucket: ${{env.STUFF_BUCKET}}
            secrets: |
                OAUTH_KEY=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/OAUTH_KEY
                DOCUMENT_API_ENDPOINT=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/DOCUMENT_API_ENDPOINT
                DOCUMENT_DATABASE_PATH=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/DOCUMENT_DATABASE_PATH
                AWS_ACCESS_KEY_ID=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/AWS_SECRET_ACCESS_KEY
                JWT_PRIVATE_KEY=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/JWT_PRIVATE_KEY

            include: |
                **/*.py
                requirements.txt
            exclude: |
                .venv 
                uv.lock
                README.md
                pyproject.toml
                .*

            execution-timeout: 1


