[project]
name = "calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crontab>=1.0.1",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "yandex-cloud-ml-sdk>=0.3.1",
]
