"""change name

Revision ID: 13208e8b4b71
Revises: ebb88b42e2c3
Create Date: 2025-03-03 15:24:52.751863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13208e8b4b71'
down_revision: Union[str, None] = 'ebb88b42e2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.drop_column('calendar_events', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('calendar_events', 'is_completed')
    # ### end Alembic commands ###
