"""empty message

Revision ID: 1a5d7e84eb1e
Revises: 23ec7e77a03b
Create Date: 2025-02-26 23:56:04.158920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a5d7e84eb1e'
down_revision: Union[str, None] = '23ec7e77a03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('winter', 'summer', 'autumn', 'spring', name='seasontypes').create(op.get_bind())
    op.create_table('cron_plant_calendar_scheduler',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season_type', postgresql.ENUM('winter', 'summer', 'autumn', 'spring', name='seasontypes', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cron_plant_calendar_scheduler')
    sa.Enum('winter', 'summer', 'autumn', 'spring', name='seasontypes').drop(op.get_bind())
    # ### end Alembic commands ###
