"""delete season type

Revision ID: 2f215c039294
Revises: e6b1b233354e
Create Date: 2025-03-03 16:05:51.414897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f215c039294'
down_revision: Union[str, None] = 'e6b1b233354e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cron_plant_calendar_scheduler', 'season_type')
    sa.Enum('winter', 'summer', 'autumn', 'spring', name='seasontypes').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('winter', 'summer', 'autumn', 'spring', name='seasontypes').create(op.get_bind())
    op.add_column('cron_plant_calendar_scheduler', sa.Column('season_type', postgresql.ENUM('winter', 'summer', 'autumn', 'spring', name='seasontypes', create_type=False), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
