"""empty message

Revision ID: 36d5f0811b39
Revises: ce2b8a3cbbc1
Create Date: 2025-02-26 19:14:24.493091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36d5f0811b39'
down_revision: Union[str, None] = 'ce2b8a3cbbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'plants', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plants', type_='unique')
    # ### end Alembic commands ###
