"""add origin_name to plant

Revision ID: 506dd94acc0d
Revises: e85414f5e759
Create Date: 2025-03-01 22:08:35.570015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '506dd94acc0d'
down_revision: Union[str, None] = 'e85414f5e759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('origin_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('plants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('plants_name_key', 'plants', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('plants_name_key', 'plants', ['name'])
    op.alter_column('plants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('plants', 'origin_name')
    # ### end Alembic commands ###
