"""add origin name unique

Revision ID: c1de4941a372
Revises: 506dd94acc0d
Create Date: 2025-03-01 22:23:37.639358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1de4941a372'
down_revision: Union[str, None] = '506dd94acc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'origin_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'plants', ['origin_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plants', type_='unique')
    op.alter_column('plants', 'origin_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
