"""empty message

Revision ID: e99958845f5d
Revises: 1a5d7e84eb1e
Create Date: 2025-02-28 20:17:32.032409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e99958845f5d'
down_revision: Union[str, None] = '1a5d7e84eb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cron_plant_calendar_scheduler', 'start_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron_plant_calendar_scheduler', sa.Column('start_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
