"""empty message

Revision ID: ebb88b42e2c3
Revises: fc4a20dd6b3f
Create Date: 2025-03-03 14:46:13.525205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebb88b42e2c3'
down_revision: Union[str, None] = 'fc4a20dd6b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('completed', sa.Boolean(), nullable=False))
    op.drop_column('calendar_events', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('calendar_events', 'completed')
    # ### end Alembic commands ###
