"""update events

Revision ID: fc4a20dd6b3f
Revises: b8f96bd67519
Create Date: 2025-03-02 20:07:19.852321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc4a20dd6b3f'
down_revision: Union[str, None] = 'b8f96bd67519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('user_plant_id', sa.Uuid(), nullable=False))
    op.drop_constraint('calendar_events_plant_id_fkey', 'calendar_events', type_='foreignkey')
    op.drop_constraint('calendar_events_user_id_fkey', 'calendar_events', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_events', 'user_plants', ['user_plant_id'], ['id'])
    op.drop_column('calendar_events', 'plant_id')
    op.drop_column('calendar_events', 'user_id')
    op.add_column('user_plants', sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_plants', 'photo_url')
    op.add_column('calendar_events', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('calendar_events', sa.Column('plant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.create_foreign_key('calendar_events_user_id_fkey', 'calendar_events', 'users', ['user_id'], ['id'])
    op.create_foreign_key('calendar_events_plant_id_fkey', 'calendar_events', 'plants', ['plant_id'], ['id'])
    op.drop_column('calendar_events', 'user_plant_id')
    # ### end Alembic commands ###
