name: Deploy

on: [push, workflow_dispatch]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      authorization: ${{ steps.filter.outputs.authorization }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          authorization:
            - 'services/auth/authorization/**'

  # JOB to build and test authorization code
  authorization:
    needs: changes
    if: ${{ needs.changes.outputs.authorization == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
            python-version: "3.12"

      - uses: yezz123/setup-uv@v4

      - name: Create Zip Archieve
        working-directory: services/auth/authorization/
        run: |
            uv pip freeze > requirements.txt
            zip -r authorization.zip * -x .venv -x uv.lock -x README.md -x pyproject.toml -x -x .*

      - name: Upload files to Object Storage
        id: s3-upload
        uses: yc-actions/yc-obj-storage-upload@v2
        with:
            yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
            bucket: auth-sevice-internal-use-bucket
            root: services/auth/authorization/
            include: |
                authorization.zip

    #   - name: Deploy Function
    #     id: sls-func
    #     uses: yc-actions/yc-sls-function@v1.0.1
    #     with:
    #         yc-sa-json-credentials: ${{secrets.YC_SA_JSON_CREDENTIALS}}
    #         folder-id: 'b1gbmkj6*******'
    #         function-name: 'github-deploy'
    #         runtime: 'nodejs16'
    #         memory: '256Mb'
    #         entrypoint: 'dist/index.handler'
    #         environment: |
    #             DEBUG=True
    #             FOO=bar
    #         include: |
    #             ./dist
    #             package.json
    #         exclude: |
    #             **/*.ts

