name: Deploy

on: [push, workflow_dispatch]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env: 
    STUFF_BUCKET: auth-sevice-internal-use-bucket
    FOLDER_ID: b1g4o9t4vgcbnkpunqeu
    SERVICE_ACCOUNT_ID: ajetqfs3ng6e1gjv7mdr
    SECRET_VERSION_ID: e6qe0ts1dc9g0h1h4kob
    SECRET_ID: e6q78o6erk6o9suemkh4

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      authorization: ${{ steps.filter.outputs.authorization }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          authorization:
            - 'services/auth/authorization/**'

  # JOB to build and test authorization code
  authorization:
    needs: changes
    if: ${{ needs.changes.outputs.authorization == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
            python-version: "3.12"

      - uses: yezz123/setup-uv@v4

      - name: Create Zip Archieve
        working-directory: services/auth/authorization/
        run: |
            uv sync
            uv pip freeze > requirements.txt

      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v2.12.0
        with:
            yc-sa-json-credentials: ${{secrets.YC_SA_JSON_CREDENTIALS}}
            folder-id: ${{env.FOLDER_ID}}
            service-account: ${{env.SERVICE_ACCOUNT_ID}}
            source-root: services/auth/authorization/
            function-name: 'authorization'
            runtime: 'python312'
            memory: '256Mb'
            entrypoint: 'main.handler'
            bucket: ${{env.STUFF_BUCKET}}
            environment: |
              GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}
              GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}
              YANDEX_CLIENT_ID=${{secrets.YANDEX_CLIENT_ID}}
              YANDEX_CLIENT_SECRET=${{secrets.YANDEX_CLIENT_SECRET}}
              DOMAIN=https://auth.hackcentrifuge.ru
            secrets: |
                OAUTH_KEY=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/OAUTH_KEY
                DOCUMENT_API_ENDPOINT=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/DOCUMENT_API_ENDPOINT
                DOCUMENT_DATABASE_PATH=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/DOCUMENT_DATABASE_PATH
                AWS_ACCESS_KEY_ID=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/AWS_SECRET_ACCESS_KEY
                JWT_PRIVATE_KEY=${{env.SECRET_ID}}/${{env.SECRET_VERSION_ID}}/JWT_PRIVATE_KEY
                
            include: |
                **/*.py
                requirements.txt
            exclude: |
                .venv 
                uv.lock
                README.md
                pyproject.toml
                .*
                
            execution-timeout: 1


